### ISSUE TITLE
Tensorflow version of the code

### ISSUE THREAD

**Issue by CGC1031** [kondratevakate/3DDeformableConvolutions#1]
Hello, thank you for your open-source code. I tried to change the code to the TensorFlow version for medical image registration. But it works poorly.  Do you have the code of the TensorFlow version? Can I learn from you?
Looking forward to your reply! Thank you very much!

**Comment by kondratevakate** [comment]
hi! not really, we are a fully torch-programming lab, so rewriting these modules in TS seems almost impossible
